
% Isoprene_Particle_Chem.m
% Generated by chuanyas@ucr.edu & haofei.zhang@ucr.edu
%
%*********************************************************
% IMPORTANT NOTE ON USAGE!
% This mechanism is designed for use with the isoprene condensed mechanism
% using 'SAPRC07tic_UCR2022_isop_NO3updated';
% This must appear after the isoprene mechanism in the "ChemFiles" structure.
%*********************************************************
%
% This mechanism follows the isoprene condesed mechanism, but handles some
% the photolysis reactions of species with peroxide (g/p phase); 

% Assumes that the SAPRC07tic_UCR2022_isop_NO3updated is called so some gas-species
% are defined already; the other new gas species are defined in this file.

% 2022-07-11 generated by chuanyang
% 
% %%  J value involved
newJ41 = 0.02.*JNO2_06; %j-value to explain loss of fresh isop SOA;
% Jdimer= 0;
% Jdimer2=0;
% %in Kroll et al volume decreases with 1-efold = 4 hours. 15 um3/cm3 at t =
% %3.5 hr and 5.5 um3/cm3 at 7.5 hr --> 8e-5 s-1. 
% newJ41=1e-4;
%% Add species, formulas, and masses to MCMSpeciesInfo.mat file
% matfilepath = '/Users/cyshen/Documents/ucr/isoprene/F0AM-WAM-2020-distribute/Setups/Isoprene mechanism/UCR2022_isop_SpeciesInfo_v2.mat';
% 
% SpeciesToAdd = {...
% 'IDHEO';'ICDHO';'IDHPO';'ICTO';'ICHNO';'IDHNO'; 'ICDNO';'IHDNO';'IHNPO';
% };
% 
% FormulasToAdd = {...
% 'C5H10O4';'C5H10O4';'C5H12O5'; 'C5H10O6';'C5H11NO6';'C5H13NO6'; 'C5H11NO7';'C5H14N2O8';'C5H13NO7';
% };
% 
% MassesToAdd = tof_exact_mass(FormulasToAdd);
% 
% SMILESToAdd = {'C[C@@](O)(CO)[C@H]1O[C@H]1O';'C[C@@](O)(CO)[C@@H](O)C=O';'C[C@@](O)(CO)[C@H](CO)OO';...'CC(C(OO)CO)(O[O])CO';...
%     'C[C@](COO)(OO)[C@@H](O)C=O';'C[C@@](O)(CO)[C@H](C=O)ON(O)O';'C[C@@](O)(CO)[C@H](CO)ON(O)O';...'CC(C(O)CO)(O[N+]([O-])=O)COO';...
%     'C[C@](CO)(OO)[C@H](C=O)ON(O)O';'C[C@](CON(O)O)(ON(O)O)[C@H](O)CO';'C[C@](CON(O)O)(OO)[C@H](O)CO';...
%     };
% 
% junk = AddToMCMSpeciesInfo(SpeciesToAdd,FormulasToAdd,MassesToAdd,SMILESToAdd,matfilepath);
% clear junk SpeciesToAdd FormulasToAdd MassesToAdd SMILESToAdd
%% Add species, formulas, and masses to MCMSpeciesInfo.mat file
% matfilepath = 'C:\Users\tiann\desktop\scy\F0AM-WAM-2020-distribute\Setups\Isoprene mechanism/UCR2022_isop_SpeciesInfo_v2.mat';
% 
% SpeciesToAdd = {...
% 'DIMER';
% };
% % 
% RO2ToAdd = {};
% 
% OAsToAdd = {...
%     'DIMER';
%     }
% % 
% AddSpecies
% MassesToAdd = tof_exact_mass(FormulasToAdd);
% % 
% SMILESToAdd = {'DIMER'};
% % 
% junk = AddToMCMSpeciesInfo(SpeciesToAdd,FormulasToAdd,MassesToAdd,SMILESToAdd,matfilepath);
% clear junk SpeciesToAdd FormulasToAdd MassesToAdd SMILESToAdd

%% gas/particle phase photolysis

i=i+1;
Rnames{i} = 'IDHPEp = OH + HO2 + 0.429MGLY + 0.429HOCCHO + 0.571GLY + 0.571HACET';
k(:,i) = newJ41;
Gstr{i,1} = 'IDHPEp';
fIDHPEp(i)=fIDHPEp(i)-1; fOH(i)=fOH(i)+1; fHO2(i)=fHO2(i)+1; fMGLY(i)=fMGLY(i)+0.429; fHOCCHO(i)=fHOCCHO(i)+0.429; fGLY(i)=fGLY(i)+0.571; fHACET(i)=fHACET(i)+0.571; 

i=i+1;
Rnames{i} = 'ICPDHp = 0.825*OH + 1.175*HO2 + 0.429*CO + 0.254*C4DH + 0.175*C4HP + 0.065*HCHO + 0.065*C4HC + 0.285*HACET + 0.285*GLY + 0.057*HOCCHO + 0.057*MGLY';
k(:,i) = newJ41;
Gstr{i,1} = 'ICPDHp';
fICPDHp(i)=fICPDHp(i)-1; fOH(i)=fOH(i)+0.825; fHO2(i)=fHO2(i)+1.175; fCO(i)=fCO(i)+0.429; fC4DH(i)=fC4DH(i)+0.254; fC4HP(i)=fC4HP(i)+0.175; fHCHO(i)=fHCHO(i)+0.065; fC4HC(i)=fC4HC(i)+0.065; fHACET(i)=fHACET(i)+0.285; fGLY(i)=fGLY(i)+0.285; fHOCCHO(i)=fHOCCHO(i)+0.057; fMGLY(i)=fMGLY(i)+0.057;  

i=i+1;
Rnames{i} = 'IDHDPp = 1.25*OH + 0.25*HOCCHO + 0.25HACET + 0.75*ICPDH + 0.75*HO2'; % this reaction is similar to the gas phase
k(:,i) = newJ41;
Gstr{i,1} = 'IDHDPp';
fIDHDPp(i)=fIDHDPp(i)-1; fOH(i)=fOH(i)+1.25; fHOCCHO(i)=fHOCCHO(i)+0.25; fHACET(i)=fHACET(i)+0.25; fICPDH(i)=fICPDH(i)+0.75; fHO2(i)=fHO2(i)+0.75; 

% i=i+1;
% Rnames{i} = 'ICHNPp = 0.8*MGLY + 0.8*OH + NO2 + 0.8*HOCCHO + 0.2*C4HP + 0.2*CO + 0.2*HO2';
% k(:,i) = newJ41;
% Gstr{i,1} = 'ICHNPp';
% fICHNPp(i)=fICHNPp(i)-1; 
% fMGLY(i)=fMGLY(i)+0.8; fHOCCHO(i)=fHOCCHO(i)+0.8; fOH(i)=fOH(i)+0.8; fNO2(i)=fNO2(i)+1; fC4HP(i)=fC4HP(i)+0.2; fCO(i)=fCO(i)+0.2;fHO2(i)=fHO2(i)+0.2;
% 
% 
% i=i+1;
% Rnames{i} = 'IDHPNp = 0.65OH + 0.7HO2 + 0.35HCHO + 0.25MACRN + 0.325HOCCHO + 0.625HACET + 0.725NO2 + 0.075MECO3 + 0.025MVKN + 0.25HPETHNL + 0.075MACROOHOH + 0.025HPAC';
% k(:,i) = newJ41;
% Gstr{i,1} = 'IDHPNp';
% fIDHPNp(i)=fIDHPNp(i)-1; 
% fOH(i)=fOH(i)+0.65; fHO2(i)=fHO2(i)+0.7; fHCHO(i)=fHCHO(i)+0.35; fMACRN(i)=fMACRN(i)+0.25; fHOCCHO(i)=fHOCCHO(i)+0.325; fHACET(i)=fHACET(i)+0.625; fNO2(i)=fNO2(i)+0.725; fMECO3(i)=fMECO3(i)+0.075; fMVKN(i)=fMVKN(i)+0.025; 
% fHPETHNL(i)=fHPETHNL(i)+0.25; fC4HP(i)=fC4HP(i)+0.075; fHPAC(i)=fHPAC(i)+0.025; 

% i=i+1;
% Rnames{i} = 'ICTPp = R6OOH + 2OH + 0.33HCHO + 0.67GLY';
% k(:,i) = newJ41 ;
% Gstr{i,1} = 'ICTPp';
% fICTPp(i)=fICTPp(i)-1; fR6OOH(i)=fR6OOH(i)+1; fOH(i)=fOH(i)+2; fHCHO(i)=fHCHO(i)+0.33; fGLY(i)=fGLY(i)+0.67; 

% i=i+1;
% Rnames{i} = 'IHNDPp = NO2 + ISOPOOHOO';
% k(:,i) = newJ41; %J54
% Gstr{i,1} = 'IHNDPp'; 
% fIHNDPp(i)=fIHNDPp(i)-1; fNO2(i)=fNO2(i)+1; fISOPOOHOO(i)=fISOPOOHOO(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'IHPDNp = 0.884*OH + 0.533*HO2 + 0.49*NO2 + 0.678*PROPNN + 0.28*HOCCHO + 0.135*ICHDN + 0.375*ETHLN + 0.094*ISOPNOO + 0.094*MVKN + 0.094*HCHO + 0.023*HPETHNL';
% k(:,i) = newJ41; %J41 + 2.0*J51; branching ratio based on photolysis
% Gstr{i,1} = 'IHPDN'; 
% fIHPDNp(i)=fIHPDNp(i)-1; fOH(i)=fOH(i)+0.884; fHO2(i)=fHO2(i)+0.533; fNO2(i)=fNO2(i)+0.49; fPROPNN(i)=fPROPNN(i)+0.678; fHOCCHO(i)=fHOCCHO(i)+0.28; fICHDN(i)=fICHDN(i)+0.135; fETHLN(i)=fETHLN(i)+0.375; 
% fISOPNOO(i)=fISOPNOO(i)+0.094; fMVKN(i)=fMVKN(i)+0.094; fHCHO(i)=fHCHO(i)+0.094; fHPETHNL(i)=fHPETHNL(i)+0.023; 
% 
% % scy added these photolysis reactions  
% 
% i=i+1;
% Rnames{i} = 'ICDPNp + hv =  OH';
% k(:,i) = newJ41;
% Gstr{i,1} = 'ICDPNp';
% fICDPNp(i)=fICDPNp(i)-1; %fICDNO(i)=fICDNO(i)+1;
% 

%% gas/particle/wall phase photolysis

% i=i+1;
% Rnames{i} = 'IDHPEw = OH + HO2 + 0.429MGLY + 0.429HOCCHO + 0.571GLY + 0.571HACET';
% k(:,i) = newJ41;
% Gstr{i,1} = 'IDHPEw';
% fIDHPEw(i)=fIDHPEw(i)-1; fOH(i)=fOH(i)+1; fHO2(i)=fHO2(i)+1; fMGLY(i)=fMGLY(i)+0.429; fHOCCHO(i)=fHOCCHO(i)+0.429; fGLY(i)=fGLY(i)+0.571; fHACET(i)=fHACET(i)+0.571; 
% 
% i=i+1;
% Rnames{i} = 'ICPDHw = 0.825OH + 1.175HO2 + 0.429CO + 0.254C4DH + 0.175MACROOHOH + 0.065HCHO + 0.065HC4 + 0.285HACET + 0.285GLY + 0.057HOCCHO + 0.057MGLY';
% k(:,i) = newJ41;
% Gstr{i,1} = 'ICPDHw';
% fICPDHw(i)=fICPDHw(i)-1; fOH(i)=fOH(i)+0.825; fHO2(i)=fHO2(i)+1.175; fCO(i)=fCO(i)+0.429; fC4DH(i)=fC4DH(i)+0.254; fMACROOHOH(i)=fMACROOHOH(i)+0.175; fHCHO(i)=fHCHO(i)+0.065; fHC4(i)=fHC4(i)+0.065; fHACET(i)=fHACET(i)+0.285; fGLY(i)=fGLY(i)+0.285; fHOCCHO(i)=fHOCCHO(i)+0.057; fMGLY(i)=fMGLY(i)+0.057;
% 
% i=i+1;
% Rnames{i} = 'IDHDPw = 1.25OH + 0.25HOCCHO + 0.25HACET + 0.75ICPDH + 0.75HO2'; % this reaction is similar to the gas phase
% k(:,i) = newJ41;
% Gstr{i,1} = 'IDHDPw';
% fIDHDPw(i)=fIDHDPw(i)-1; fOH(i)=fOH(i)+1.25; fHOCCHO(i)=fHOCCHO(i)+0.25; fHACET(i)=fHACET(i)+0.25; fICPDH(i)=fICPDH(i)+0.75; fHO2(i)=fHO2(i)+0.75; 
% 
% i=i+1;
% Rnames{i} = 'ICHNPw = 0.8MGLY + 0.8OH + NO2 + 0.8HOCCHO + 0.1MVKOOHOH + 0.1MACROOHOH + 0.2CO + 0.2HO2';
% k(:,i) = newJ41;
% Gstr{i,1} = 'ICHNPw';
% fICHNPw(i)=fICHNPw(i)-1; 
% fMGLY(i)=fMGLY(i)+0.8; fHOCCHO(i)=fHOCCHO(i)+0.8; fOH(i)=fOH(i)+0.8; fNO2(i)=fNO2(i)+1; fMVKOOHOH(i)=fMVKOOHOH(i)+0.1; fMACROOHOH(i)=fMACROOHOH(i)+0.1; fCO(i)=fCO(i)+0.2;fHO2(i)=fHO2(i)+0.2;
% 
% 
% i=i+1;
% Rnames{i} = 'IDHPNw = 0.65OH + 0.7HO2 + 0.35HCHO + 0.25MACRN + 0.325HOCCHO + 0.625HACET + 0.725NO2 + 0.075MECO3 + 0.025MVKN + 0.25HPETHNL + 0.075MACROOHOH + 0.025HPAC';
% k(:,i) = newJ41;
% Gstr{i,1} = 'IDHPNw';
% fIDHPNw(i)=fIDHPNw(i)-1; 
% fOH(i)=fOH(i)+0.65; fHO2(i)=fHO2(i)+0.7; fHCHO(i)=fHCHO(i)+0.35; fMACRN(i)=fMACRN(i)+0.25; fHOCCHO(i)=fHOCCHO(i)+0.325; fHACET(i)=fHACET(i)+0.625; fNO2(i)=fNO2(i)+0.725; fMECO3(i)=fMECO3(i)+0.075; fMVKN(i)=fMVKN(i)+0.025; 
% fHPETHNL(i)=fHPETHNL(i)+0.25; fMACROOHOH(i)=fMACROOHOH(i)+0.075; fHPAC(i)=fHPAC(i)+0.025; 
% 
% i=i+1;
% Rnames{i} = 'ICTPw = R6OOH + 2OH + 0.33HCHO + 0.67GLY';
% k(:,i) = newJ41 ;
% Gstr{i,1} = 'ICTPw';
% fICTPw(i)=fICTPw(i)-1; fR6OOH(i)=fR6OOH(i)+1; fOH(i)=fOH(i)+2; fHCHO(i)=fHCHO(i)+0.33; fGLY(i)=fGLY(i)+0.67; 
% 
% i=i+1;
% Rnames{i} = 'IHNDPw = NO2 + ISOPOOHOO1';
% k(:,i) = newJ41; %J54
% Gstr{i,1} = 'IHNDPw'; 
% fIHNDPw(i)=fIHNDPw(i)-1; fNO2(i)=fNO2(i)+1; fISOPOOHOO1(i)=fISOPOOHOO1(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'IHPDNw = 0.884OH + 0.533HO2 + 0.49NO2 + 0.678PROPNN + 0.28HOCCHO + 0.135ICHDN + 0.375ETHLN + 0.094ISOPNOO + 0.094MVKN + 0.094HCHO + 0.023HPETHNL';
% k(:,i) = newJ41; %J41 + 2.0*J51; branching ratio based on photolysis
% Gstr{i,1} = 'IHPDNw'; 
% fIHPDNw(i)=fIHPDNw(i)-1; fOH(i)=fOH(i)+0.884; fHO2(i)=fHO2(i)+0.533; fNO2(i)=fNO2(i)+0.49; fPROPNN(i)=fPROPNN(i)+0.678; fHOCCHO(i)=fHOCCHO(i)+0.28; fICHDN(i)=fICHDN(i)+0.135; fETHLN(i)=fETHLN(i)+0.375; 
% fISOPNOO(i)=fISOPNOO(i)+0.094; fMVKN(i)=fMVKN(i)+0.094; fHCHO(i)=fHCHO(i)+0.094; fHPETHNL(i)=fHPETHNL(i)+0.023; 
% 
% % scy added these photolysis reactions  
% 
% i=i+1;
% Rnames{i} = 'ICDPNw + hv =  OH';
% k(:,i) = newJ41;
% Gstr{i,1} = 'ICDPNw';
% fICDPNw(i)=fICDPNw(i)-1; %fICDNO(i)=fICDNO(i)+1;
%% dimer formation v1
% 
% i=i+1;
% Rnames{i} = 'IDHPEp + IDHPEp = DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHPEp'; Gstr{i,2} = 'IDHPEp';
% fIDHPEp(i)=fIDHPEp(i)-1; fIDHPEp(i)=fIDHPEp(i)-1; fDIMER(i)=fDIMER(i)+1;  
% 
% i=i+1;
% Rnames{i} = 'ICPDHp + ICPDHp = DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICPDHp'; Gstr{i,2} = 'ICPDHp';
% fICPDHp(i)=fICPDHp(i)-1; fICPDHp(i)=fICPDHp(i)-1; fDIMER(i)=fDIMER(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'IDHDPp + IDHDPp = DIMER'; % this reaction is similar to the gas phase
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHDPp'; Gstr{i,2} = 'IDHDPp';
% fIDHDPp(i)=fIDHDPp(i)-1; fIDHDPp(i)=fIDHDPp(i)-1; fDIMER(i)=fDIMER(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'ICHNPp + ICHNPp = DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICHNPp'; Gstr{i,2} = 'ICHNPp';
% fICHNPp(i)=fICHNPp(i)-1; fICHNPp(i)=fICHNPp(i)-1; fDIMER(i)=fDIMER(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'IDHPNp + IDHPNp = DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHPNp'; Gstr{i,2} = 'IDHPNp';
% fIDHPNp(i)=fIDHPNp(i)-1;  fIDHPNp(i)=fIDHPNp(i)-1; fDIMER(i)=fDIMER(i)+1; 
% 
% i=i+1;
% Rnames{i} = 'ICTPp + ICTPp =  DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICTPp'; Gstr{i,2} = 'ICTPp';
% fICTPp(i)=fICTPp(i)-1; fICTPp(i)=fICTPp(i)-1; fDIMER(i)=fDIMER(i)+1;
% 
% i=i+1;
% Rnames{i} = 'ICDPNp + ICDPNp =  DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICDPNp'; Gstr{i,2} = 'ICDPNp';
% fICDPNp(i)=fICDPNp(i)-1; fICDPNp(i)=fICDPNp(i)-1; fDIMER(i)=fDIMER(i)+1;
% 
% i=i+1;
% Rnames{i} = 'IHPDNp + IHPDNp =  DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IHPDNp'; Gstr{i,2} = 'IHPDNp';
% fIHPDNp(i)=fIHPDNp(i)-1;  fIHPDNp(i)=fIHPDNp(i)-1; fDIMER(i)=fDIMER(i)+1;
% 
% i=i+1;
% Rnames{i} = 'IHNDPp + IHNDPp =  DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IHNDPp'; Gstr{i,2} = 'IHNDPp';
% fIHNDPp(i)=fIHNDPp(i)-1; fIHNDPp(i)=fIHNDPp(i)-1; fDIMER(i)=fDIMER(i)+1;

%% dimer formation v2

% i=i+1;
% Rnames{i} = 'IDHPEp  = 0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHPEp'; 
% fIDHPEp(i)=fIDHPEp(i)-1; fDIMER(i)=fDIMER(i)+0.5;  
% 
% i=i+1;
% Rnames{i} = 'ICPDHp = 0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICPDHp'; 
% fICPDHp(i)=fICPDHp(i)-1; fDIMER(i)=fDIMER(i)+0.5; 

% i=i+1;
% Rnames{i} = 'IDHDPp  = 0.5DIMER'; % this reaction is similar to the gas phase
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHDPp'; 
% fIDHDPp(i)=fIDHDPp(i)-1;  fDIMER(i)=fDIMER(i)+0.5; 

% i=i+1;
% Rnames{i} = 'ICHNPp  = 0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICHNPp'; 
% fICHNPp(i)=fICHNPp(i)-1; fDIMER(i)=fDIMER(i)+0.5; 
% 
% i=i+1;
% Rnames{i} = 'IDHPNp  = 0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IDHPNp'; 
% fIDHPNp(i)=fIDHPNp(i)-1;  fDIMER(i)=fDIMER(i)+0.5; 
% 
% % i=i+1;
% % Rnames{i} = 'ICTPp  =  0.5DIMER';
% % k(:,i) = Jdimer;
% % Gstr{i,1} = 'ICTPp'; 
% % fICTPp(i)=fICTPp(i)-1;  fDIMER(i)=fDIMER(i)+0.5;
% 
% i=i+1;
% Rnames{i} = 'ICDPNp  =  0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ICDPNp'; 
% fICDPNp(i)=fICDPNp(i)-1;  fDIMER(i)=fDIMER(i)+0.5;
% 
% i=i+1;
% Rnames{i} = 'IHPDNp  =  0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IHPDNp'; 
% fIHPDNp(i)=fIHPDNp(i)-1;   fDIMER(i)=fDIMER(i)+0.5;
% 
% i=i+1;
% Rnames{i} = 'IHNDPp  =  0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'IHNDPp';
% fIHNDPp(i)=fIHNDPp(i)-1;  fDIMER(i)=fDIMER(i)+0.5;

% i=i+1;
% Rnames{i} = 'ITHNp  =  0.5DIMER';
% k(:,i) = Jdimer;
% Gstr{i,1} = 'ITHNp';
% fITHNp(i)=fITHNp(i)-1;  fDIMER(i)=fDIMER(i)+0.5;

% i=i+1;
% Rnames{i} = 'IHMMLp + MGAp =  DIMER';
% k(:,i) = Jdimer2;
% Gstr{i,1} = 'IHMMLp'; Gstr{i,2}='MGAp';
% fIHMMLp(i)=fIHMMLp(i)-1; fMGAp(i)=fMGAp(i)-1; fDIMER(i)=fDIMER(i)+1;

% i=i+1;
% Rnames{i} = 'IHMMLp + NMGAp =  DIMER';
% k(:,i) = Jdimer2;
% Gstr{i,1} = 'IHMMLp'; Gstr{i,2}='NMGAp';
% fIHMMLp(i)=fIHMMLp(i)-1; fNMGAp(i)=fNMGAp(i)-1; fDIMER(i)=fDIMER(i)+1;



